import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://instabraindevelopment.instabrainstage.io/');
  await page.locator('#hero-cta-select').selectOption('insta-adb');
  await page.goto('https://instabraindevelopment.instabrainstage.io/quote/start/a47cd409-a811-4356-9194-8e1ab9e38327?opportunityId=380340a7-6a07-4758-b3a8-edcedab7616f');
  await page.locator('div').nth(5).click();
  await page.getByRole('img', { name: 'InstaBrain Logo' }).click();
  await page.getByRole('button', { name: 'Continue Later' }).click();
  await page.getByRole('dialog', { name: 'Continue Later' }).click();
  await page.getByRole('img', { name: 'ib-logo' }).click();
  await page.getByRole('heading', { name: 'Continue Later' }).click();
  await page.locator('div').filter({ hasText: 'Phone Number Verify' }).nth(3).click();
  await page.getByText('Phone Number').click();
  await page.getByRole('textbox', { name: 'Enter Phone' }).click();
  await page.getByRole('textbox').fill('(516) 929-8899');
  await page.getByRole('button', { name: 'Verify' }).click();
  await page.getByTestId('DriveFileRenameOutlineIcon').click();
  await page.getByRole('button', { name: 'Verify' }).click();
  await page.locator('div').filter({ hasText: 'Verification CodeResend or' }).nth(5).click();
  await page.getByText('Verification Code').click();
  await page.getByRole('textbox', { name: 'Please enter verification' }).click();
  await page.getByRole('textbox', { name: 'Please enter verification' }).fill('0');
  await page.getByRole('textbox', { name: 'Digit 2' }).fill('0');
  await page.getByRole('textbox', { name: 'Digit 3' }).fill('8');
  await page.getByRole('textbox', { name: 'Digit 4' }).fill('7');
  await page.getByRole('textbox', { name: 'Digit 5' }).fill('6');
  await page.getByRole('textbox', { name: 'Digit 6' }).fill('2');
  await page.getByText('Resend or get a call in').click();
  await page.getByText(':10').click();
  await page.getByRole('dialog', { name: 'ib-logo Your application has' }).click();
  await page.getByRole('img', { name: 'ib-logo' }).click();
  await page.getByRole('heading', { name: 'ib-logo Your application has' }).click();
  await page.getByRole('heading', { name: 'ib-logo Your application has' }).click();
  await page.locator('div').filter({ hasText: 'We have sent you the' }).nth(5).click();
  await page.getByText('We have sent you the').click();
  await page.getByText('You can complete your').click();
  await page.getByRole('button', { name: 'Copy Application Link' }).click();
  await page.getByText('The link has been copied to').click();
  await page.locator('div').nth(3).click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.locator('circle').click();
  await page.getByText('Agent:').click();
  await page.getByText('Agent: InstaBrain Deve...').click();
  await page.getByText('Agent: InstaBrain Deve...I').click();
  await page.getByText('Did You Know?').click();
  await page.getByText('Did You Know?MYTHApplying for').click();
  await page.getByText('Did You Know?MYTHApplying for').click();
  await page.getByText('Did You Know?MYTHApplying for').click();
  await page.getByText('of 3').click();
  await page.getByText('of 30%').click();
  await page.locator('.MuiPaper-root').click();
  await page.getByRole('img', { name: 'icon' }).click();
  await page.getByRole('heading', { name: 'What is your sex assigned at' }).click();
  await page.getByText('What is your sex assigned at birth?MaleFemale').click();
  await page.getByTestId('KeyboardBackspaceIcon').click();
  await page.locator('img').nth(4).click();
});