import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://instabraindevelopment.instabrainstage.io/');
  await page.locator('#hero-cta-select').selectOption('term-to-pure-term-to-adb');
  await page.goto('https://instabraindevelopment.instabrainstage.io/quote/start/674079a9-5f85-410f-8dc9-1029d65c42a8?opportunityId=f1f4b027-f12e-49fa-bab4-d56bd5e8fe63');
  await page.getByRole('button', { name: 'Can\'t find your state?' }).click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.getByRole('button', { name: 'Can\'t find your state?' }).click();
  await page.getByRole('button', { name: 'Back to Home' }).click();
  await page.locator('#hero-cta-select').selectOption('term-to-pure-term-to-adb');
  //await page.goto('https://instabraindevelopment.instabrainstage.io/quote/start/0b587702-bcb9-4c9d-8b64-23b020c5eb12?opportunityId=f132297f-ab65-4eb5-b458-d97056a19823');
  await page.getByRole('button', { name: 'Arizona' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByPlaceholder('Enter Age').click();
  await page.getByPlaceholder('Enter Age').fill('27');
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByText('Female').click();
  await page.getByText('No', { exact: true }).click();
  await page.getByText('Excellent').click();
  // === Coverage Amount Section ===
  await expect(page.locator('#coverage-basics-container')).toBeVisible({ timeout:15000 });
  // Click to open the Coverage Amount dropdown (better than clicking lone "$")
  await page.locator('#coverage-basics-container').getByText(/^\$\d/).click({ force: true});
  await page.waitForTimeout(1000);
  await page.getByRole('option', { name: '$1,000,000' }).click({ force: true});
  await expect(page.locator('#coverage-basics-container')).toBeVisible();
  //getByText(/30 Years/).click();
 //await page.locator('#coverage-basics-container').getByText(/30 Years/).click();
  await expect(page.locator('#coverage-basics-container')).toBeVisible({ timeout: 15000 });
  await page.locator('#coverage-basics-container').getByText(/^\$\d/).click({ force: true });
  await page.waitForTimeout(500);
  await page.locator('#coverage-basics-container').getByText('Years').click();
  //await page.waitForTimeout(500);
  await page.getByRole('option', { name: '30 Years' }).click();
  await page.getByRole('button', { name: 'Apply Now' }).click();
  await page.getByLabel('First Name');
  //await page.waitForTimeout(900);
  const firstNameInput = page.locator('input[name="e578ad70-2312-4021-b228-08abd4e2a830"]');
  await page.waitForLoadState('networkidle');
  await firstNameInput.fill('Bhakti');
  //await page.waitForTimeout(50000);
  //await page.locator('input[name="e578ad70-2312-4021-b228-08abd4e2a830"]').fill('Bhakti');
  //await page.waitForTimeout(900);
  await page.getByLabel('Last Name');
  const lastNameInput = page.locator('input[name="5667d84b-9877-439e-8e49-156d51186578"]');
  await lastNameInput.fill('Gajjar');
  await page.waitForTimeout(50000);
  //await page.locator('input[name="5667d84b-9877-439e-8e49-156d51186578"]').fill('Gajjar');
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: 'Back' }).click();
  //await page.locator('input[name="e578ad70-2312-4021-b228-08abd4e2a830"]').click();
  await page.getByRole('button', { name: 'Back' }).click();
  await page.getByRole('button', { name: 'Back to Quote' }).click();
  await page.getByTestId('KeyboardBackspaceIcon').click();
  await page.getByTestId('KeyboardBackspaceIcon').click();
  await page.getByTestId('KeyboardBackspaceIcon').click();
  await page.getByTestId('KeyboardBackspaceIcon').click();
  await page.getByRole('button', { name: 'Arizona' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByText('Female').click();
  await page.getByText('Excellent').click();
  await page.getByRole('button', { name: 'Apply Now' }).click();
});